### ISSUE TITLE
Error in description? Not _quasi_-Monte Carlo?

### ISSUE THREAD

**Issue by droodman** [PharmCat/MvNormalCDF.jl#15]
The readme says "Quasi-Monte-Carlo numerical computation of multivariate normal probabilities." However, it looks to me like the "Quasi" bit is wrong. If the code uses random numbers, then it's just Monte Carlo simulation. If it uses number-theoretic, deterministic sequences such as Halton sequences---which maximize uniformity of coverage of the unit hypercube at the expense of independence of different draws---it is "quasi Monte Carlo."

**Comment by PharmCat** [comment]
Hi! Yes, it use Richtmyer generator.

**Comment by droodman** [comment]
Ah, I see. Thank you. I think it would be good to document that and explain the role of the rng argument.
