### ISSUE TITLE
UndefVarError: `cov2cor` not defined

### ISSUE THREAD

**Issue by ngiann** [PharmCat/MvNormalCDF.jl#5]
Under MvNormalCDF v0.1.0, the following example leads to an error:
```
d=2
A = Matrix(1.0*I,d,d)
μ = zeros(d)
a=zeros(d)
b=ones(d)*Inf

(p,e) = mvnormcdf(μ, A, a, b)
```
The error reads "UndefVarError: `cov2cor` not defined"

**Comment by ngiann** [comment]
My mistake: `μ` is set at the boundary of the truncation! Sorry.
Perhaps a message would be helpful for idiots like me.

**Comment by PharmCat** [comment]
> Under MvNormalCDF v0.1.0, the following example leads to an error:
> 
> ```
> d=2
> A = Matrix(1.0*I,d,d)
> μ = zeros(d)
> a=zeros(d)
> b=ones(d)*Inf
> 
> (p,e) = mvnormcdf(μ, A, a, b)
> ```
> 
> The error reads "UndefVarError: `cov2cor` not defined"

seems it work in 0.2.5

**Comment by ngiann** [comment]
unresolved deps automatically installed 0.0.1.
